# Site settings
title: Noor Eddin Amer
description: 'Software Developer'
url: 'http://nooralasa.github.io/' # githubusername.github.io
baseurl: '/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Noor Eddin Amer'
  email: nooralasa@gmail.com
  twitter_username: nooralasa
  facebook_username: nooralasa
  github_username:  nooralasa
  linkedin_username:  nooralasa

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
